version: "3"
services:
  restapi:
     build: ./app
     image: sunilpawar09999/app:latest
     volumes:
       - "./app/pythonAPI/RestAPI2/src:/restapi"
     depends_on:
       - db
     ports:
       - "8080:5000"
     environment:
       - DATABASE_HOST=db
  db:
     build: ./mysql
     image: sunilpawar09999/db:latest
     expose:
       - "3306"
     ports:
       - "3306:3306"
     command: [--default-authentication-plugin=mysql_native_password] 

